"""agrega_tiempo_limite_foto_y_codigo

Revision ID: 64f5b2cb627e
Revises: d094161b64b5
Create Date: 2026-06-12 01:59:12.982159

"""
from alembic import op
import sqlalchemy as sa



revision = '64f5b2cb627e'
down_revision = 'd094161b64b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donaciones_lotes', sa.Column('tiempo_limite', sa.DateTime(timezone=True), nullable=True))
    op.add_column('donaciones_lotes', sa.Column('foto_url', sa.String(), nullable=True))
    op.add_column('reservas', sa.Column('codigo_verificacion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'codigo_verificacion')
    op.drop_column('donaciones_lotes', 'foto_url')
    op.drop_column('donaciones_lotes', 'tiempo_limite')
    # ### end Alembic commands ###
