"""add horarios y caducidad a donacion_lote

Revision ID: 6faf57d5163b
Revises: 5beb1f6aba43
Create Date: 2026-07-21 00:15:35.988717

"""
from alembic import op
import sqlalchemy as sa



revision = '6faf57d5163b'
down_revision = '5beb1f6aba43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donaciones_lotes', sa.Column('hora_inicio', sa.Time(), nullable=True))
    op.add_column('donaciones_lotes', sa.Column('hora_fin', sa.Time(), nullable=True))
    op.add_column('donaciones_lotes', sa.Column('fecha_hora_caducidad', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donaciones_lotes', 'fecha_hora_caducidad')
    op.drop_column('donaciones_lotes', 'hora_fin')
    op.drop_column('donaciones_lotes', 'hora_inicio')
    # ### end Alembic commands ###
