"""actualizar_modelos_tarea3

Revision ID: d260471906c7
Revises: 64f5b2cb627e
Create Date: 2026-06-12 02:11:06.963750

"""
from alembic import op
import sqlalchemy as sa



revision = 'd260471906c7'
down_revision = '64f5b2cb627e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
